##Universidad Autonoma de Aguascalientes
##Depoartamento de Ciencias de la Computacion
##Carrera Ingenieria en Computacopn Inteligente
##Curso Inteligencia Artificial (McCollouc Pitts)
##Maestro: Dr. Francisco Javier Luna Rosas
##Alumno: Martin Isai Nuñez Villeda
##semestre :Agosto_Diciembre del 2024
##Practica No.6

# Insertamos las librerias necesarias

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split # type: ignore
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

#from pandas import DataFrame

## Cargamos la DataFrame   

In [ ]:
os.chdir("C:C:\\Users\\Isai Nuñez\\Documents\\3er semestres\\primer parcial\\Inteligencia artificial\\Extras")
datos = pd.read_csv('iris.csv', delimiter=';', decimal=".")
print(datos.shape)
print(datos.head())
#print(datos.info())

(150, 5)
   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa


## Elimina la variable categorica, deja las variables predictorias en x

In [ ]:
X = datos.iloc[:,:4];
print(X.head())

   s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2


## Deja la variable a predecir en y

In [ ]:
y = datos.iloc[:,4:5]
print(y.head())

     tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa


## Se separan los datos con el 70% de los datos para entrenamiento y el 30% para el testing

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, random_state = 0)

## Mediante el constructpr inicializa la instancia_red

### Nota: Por defecto usa 100 nodos en cada capa oculta, "solver" es el metodo de optimizacion

In [ ]:
instancia_red = MLPClassifier()
print(instancia_red)

MLPClassifier()


## Entrena el modelo llamado al metodo fit

In [ ]:
print(y_train.iloc[:,0].values)
print(X_train)
instancia_red.fit(X_train, y_train.iloc[:,0].values)

['versicolor' 'virginica' 'virginica' 'virginica' 'virginica' 'versicolor'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'virginica' 'virginica'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'virginica' 'virginica' 'virginica' 'virginica' 'setosa'
 'setosa' 'virginica' 'virginica' 'setosa' 'virginica' 'setosa'
 'virginica' 'virginica' 'setosa' 'setosa' 'virginica' 'setosa' 'setosa'
 'setosa' 'versicolor' 'virginica' 'virginica' 'setosa' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'setosa' 'setosa' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'setosa' 'virginica'
 'setosa' 'virginica' 'setosa' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'virginica' 'virginica'
 '

c:\Users\monts\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

## Imprime las predicciones en testing

In [ ]:
print("Las predicciones en Teating son: {}".format(instancia_red.predict(X_test)))

Las predicciones en Teating son: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'virginica' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'virginica' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'virginica'
 'setosa' 'setosa']


## Funcion para calcular los indices de calidad de la preduccion

In [ ]:
def indices_general(MC, nombres = None):
    precision_global = np.sum(MC.diagonal())/np.sum(MC)
    error_global = 1 - precision_global
    precision_categoria = pd.DataFrame(MC.diagonal()/np.sum(MC, axis=1)).T
    if nombres != None:
        precision_categoria.columns = nombres
    return {"Matriz de confucion":MC,
            "Precision Global": precision_global,
            "Error Global": error_global,
            "Precision por categoria": precision_categoria}


## Indices de calidad del modelo

In [ ]:
prediccion = instancia_red.predict(X_test)
MC = confusion_matrix(y_test, prediccion)
indices = indices_general(MC,list(np.unique(y)))

for k in indices:
    print("\n%s:\n%s"%(k, str(indices[k])))


Matriz de confucion:
[[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]

Precision Global:
0.9333333333333333

Error Global:
0.06666666666666665

Precision por categoria:
   setosa  versicolor  virginica
0     1.0    0.833333        1.0


# Conclusion

En esta práctica, utilizamos un algoritmo de aprendizaje automático para clasificar clases no lineales, implementando una Red Neuronal con Retropropagación (NNBP). La NNBP se usó para clasificar diferentes especies de la flor iris: setosa, versicolor y virginica. Las características consideradas fueron la longitud y el ancho del pétalo, así como la longitud y el ancho del sépalo.

##Referencias
### https: SCIKIT-LEARN (Machine Learning in Python 2024) https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.htm#sklearn.neural_network.MLPClassifier